### ISSUE TITLE
Wrong exception error in case class with scala.Option

### ISSUE THREAD

**Issue by DDuarte** [jcazevedo/moultingyaml#1]
``` scala
case class TestsConfiguration(
  before_jobs: Option[List[String]],
  jobs: List[JobDefinition],
  after_jobs: Option[List[String]])

// ...

object YamlProtocol extends DefaultYamlProtocol {
  implicit val testsConfigurationFormat = yamlFormat3(TestsConfiguration)
  // ...
}
```

`"".parseYaml.convertTo[TestsConfiguration]` throws a `DeserializationException: YamlObject expected in field 'before_jobs'` however I was expecting that the expected field was `jobs` and not `before_jobs` (which is an Option)

**Comment by ruippeixotog** [comment]
The message shown was clearly misleading. It means that it tried to read the `before_jobs` field (existing or not) from a `YamlObject`, but it found a `YamlNull` instead (apparently SnakeYAML parses empty documents as `YamlNull`).

I honestly don't know how empty documents should be parsed. Ruby's YAML library simply refuses to parse it (but [this issue](https://github.com/tenderlove/psych/issues/149) about that is open):

``` ruby
2.2.0 :011 > require 'yaml'
 => true
2.2.0 :012 > YAML.load("a: 4")
 => {"a"=>4}
2.2.0 :013 > YAML.load("")
 => false
```

**Comment by jcazevedo** [comment]
I don't mind having empty documents (i.e. `""`, not `"{}"`) parsed as `YamlNull`. The exception message was improved in PR #5.
