### ISSUE TITLE
Converting YamlNumber/Date/etc items to String throws exception

### ISSUE THREAD

**Issue by TJC** [jcazevedo/moultingyaml#11]
Maybe I'm just Doing It Wrong, but I keep hitting cases where I want a string, but attempting to convert to it results in errors because YamlNumbers, Dates, etc are found in the AST instead of a String.

Eg. `myYamlValue.convertTo[String]` throws a deserialisation exception `YamlNumber found where YamlString expected`.

Consider the case where you have an array in YAML, and the items were intended to all be strings, but some happened to look like numbers. Say, umm:

```
Contacts:
  - +61-403-123-456
  - (08) 756 4321
  - 085551234
```

Could MoultingYaml make this handling easier for us?

**Comment by jcazevedo** [comment]
Without explicit typing [through tags](http://yaml.org/spec/1.2/spec.html#id2761292), and according to the [YAML specification](http://yaml.org/type/int.html), scalars matching the canonical format of an integer should be represented by a native integer data type.

In your case, you can modify your document so that the type becomes explicit, either by wrapping the elements in double quotes:

```
Contacts:
  - "+61-403-123-456"
  - "(08) 756 4321"
  - "085551234"
```

Or by providing explicit type tags:

```
Contacts:
  - !!str +61-403-123-456
  - !!str (08) 756 4321
  - !!str 085551234
```

If modifying the document is not an option, you can also create your own domain object and provide a custom `YamlFormat`:

``` scala
import net.jcazevedo.moultingyaml
import net.jcazevedo.moultingyaml._
import net.jcazevedo.moultingyaml.DefaultYamlProtocol._

case class Contact(str: String)

implicit val contactReader = new YamlFormat[Contact] {
  def read(v: YamlValue) = v match {
    case YamlString(s) => Contact(v.convertTo[String])
    case YamlNumber(n) => Contact(n.toString)
    case other => deserializationError("")
  }
  def write(c: Contact) = ???
}

val str = """
Contacts:
  - +61-403-123-456
  - (08) 756 4321
  - 085551234
"""
```

``` scala
scala> str.parseYaml.convertTo[Map[String, List[Contact]]]
res0: Map[String,List[Contact]] = Map(Contacts -> List(Contact(+61-403-123-456), Contact((08) 756 4321), Contact(8.5551234E7)))
```

From MoultingYAML's point of view, the alternative would be to change the `YamlFormat` of `Strings` to be able to read from `YamlNumber` or other types. However, the YAML specification states the following:

> A YAML processor need not expose the serialization or representation stages. It may translate directly between native data structures and a character stream (dump and load in the diagram above). However, such a direct translation should take place so that the native data structures are constructed only from information available in the representation.

As such, I'm against adding a facility to the library for converting from the node graph to a native data structure that is application specific. I believe it should be the user to deal with such ambiguities.

**Comment by TJC** [comment]
There's a large existing codebase (not in Scala or Java) that uses the pre-existing YAML, so adjusting it is not an option.

I had come up with the method of using a custom reader to get my code working, but.. it's really pretty ugly. You end up with something like this that you then call from a lot of custom readers:

``` scala
def stringifyYamlValue(yv: YamlValue): String = yv match {
  case YamlString(s) => s
  case YamlNumber(n) => n.toString
  case YamlDate(d) => ISODateTimeFormat.dateTime.print(d)
  case YamlBoolean(true) => "true"
  case YamlBoolean(false) => "false"
  case YamlNull => // is this an exception or an empty string?
  case _ => throw Something("I can't deserialise this in a meaningful way")
}

def read(v: YamlValue) = new YamlFormat[CustomMap] =
  v.asYamlObject.fields.map{ case (k,v) => (stringifyYamlValue(k), stringifyYamlValue(v)) }

```

I accept that, as you say, your code already meets the YAML specification.
But everyone who uses it will probably need to re-implement the almost identical stringification code. Some will do it well, some will do it badly.

It'd be great and save everyone work, if you could find a way to implement it as Best Practice, and include it in the core library.

**Comment by ruippeixotog** [comment]
A few comments about this.

First, once you create a custom YAML format for strings and for other primitives you want your deserialization to be more flexible, you can use it as a replacement for the strict one:

``` scala
import net.jcazevedo.moultingyaml._
import net.jcazevedo.moultingyaml.DefaultYamlProtocol.{ StringYamlFormat => _, _ }

implicit val stringFormat = new YamlFormat[String] {
  def read(yaml: YamlValue) = yaml match {
    case YamlString(s) => s
    case YamlNumber(n) => n.toString
    case YamlDate(d) => d.toString // ISODateTimeFormat.dateTime.print(d)
    case YamlBoolean(true) => "true"
    case YamlBoolean(false) => "false"
    case YamlNull => "" // is this an exception or an empty string?
    case _ => throw new Exception("I can't deserialise this in a meaningful way")
  }

  def write(str: String) = YamlString(str)
}

"[3, aa, 1d]".parseYaml.convertTo[List[String]]
// res1: List[String] = List(3, aa, 1d)

"""
a: 56
b: aa
c: 06765""".parseYaml.convertTo[Map[String, String]]
// res2: Map[String,String] = Map(b -> aa, c -> 3573, a -> 56)
```

You can implement this once in an object and then import it every time you want flexibility. You can even create your own replacement for `DefaultYamlProtocol`, shielding client code from those details.

Second, I don't think there is some "Best Practice", application-agnostic way to deal with pseudo-ambiguity in YAML. In your example you give some examples of ambiguous situations. `YamlNull` is a primitive in YAML, represented by `null` or `~` - which one would you print? As a null indicates semantically that there is no value available for that field, would it be more correct to return `""`, `"null"`, `null`? Boolean values can be represented in YAML by any one of `Y`, `true`, `Yes`, `ON`, `n`, `FALSE`, `No` and `off`. When force-read as a string, would a library be obliged to return the exact value used in the representation? That would make the intermediate representation of a YAML document way heavier than it was supposed to be, as it would always have to store the original representation of the value. And even so, I believe that different applications would like to handle those cases in different ways.
