### ISSUE TITLE
`pallete` should be `palette` in README.md

### ISSUE THREAD

**Issue by akauppi** [jcazevedo/moultingyaml#19]
First of all, thanks for the project. The promise of being able to work as easily with YAML as with JSON (using spray-json) is wonderful!

The one documentation bug I noticed is misspelling of "palette". It's probably a language issue, but since the rest of the README is in English, it should be "palette". 8 times

http://www.etymonline.com/index.php?search=Palette

**Comment by jcazevedo** [comment]
Thanks for pointing that out! Fixed it in 94e99b8.
