### ISSUE TITLE
"true" was not converted to string

### ISSUE THREAD

**Issue by DDuarte** [jcazevedo/moultingyaml#2]
Parsing the following yaml:

``` yaml
- name: job1
  metric: bad
  script:
    - true
```

with the following definition:

``` scala
case class JobDefinition(
  name: String,
  metric: String,
  before_script: Option[List[String]],
  script: List[String],
  after_script: Option[List[String]])

object YamlProtocol extends DefaultYamlProtocol {
  implicit val jobDefinitionFormat = yamlFormat5(JobDefinition)
}
```

fails with the following exception: `DeserializationException: Expected String as YamlString, but got YamlBoolean(true)`

**Comment by jcazevedo** [comment]
This issue is fixed in #4. 

The same problem is still present when processing dates (which are parsed as `YamlDate`) and null values (which are parsed as `YamlNull`). I'm still not sure if we should store the original string representation in `YamlDates`.

**Comment by ruippeixotog** [comment]
After reading some stuff on YAML parsing, I am not convinced that the correct behavior should be to parse/convert "literal" booleans and numbers directly as strings.

The Ruby YAML library parses things as strings [only when they can't be parsed as any other type](http://yaml.org/YAML_for_ruby.html#strings), while SnakeYAML attributes implicit tags to untagged nodes [according to regular expressions](https://code.google.com/p/snakeyaml/wiki/Documentation#Tags) in which numbers and booleans clearly precede strings, as seen in the issue. The [specification](http://yaml.org/spec/1.1/current.html#id858600) is not clear on this, but the examples it shows, `canonical: 12345 (...) string: '12345'`, seem to suggest that numbers should be quoted to be treated as strings (a position shared by [this guy on StackOverflow](http://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml/22235064#22235064)). Finally, a sentence that convinced me a few paragraphs below in the spec:

> A YAML processor need not expose the serialization or representation stages. It may **translate directly between native data structures and a character stream** (dump and load in the diagram above). However, such a direct translation should take place so that the native data structures are constructed **only from information available in the representation**.

That seems to indicate that it is not correct to parse values based on application code, as it is not contained in the document representation. Of course, when using a `YamlReader` you are explicitly asking for a value of a certain type... but doing a conversion at that time is akin to what weakly typed languages (i.e. JavaScript, Bash) do, and that's not very nice.

A practical solution to @DDuarte's case is to wrap ambiguous commands in quotes, and I think I prefer that to doing implicit conversions between types. But if you think we should do that, I'll accept the pull request.

**Comment by jcazevedo** [comment]
> A YAML processor need not expose the serialization or representation stages. It may translate directly between native data structures and a character stream (dump and load in the diagram above). However, such a direct translation should take place so that the native data structures are constructed only from information available in the representation.

Even though I don't think we're violating that, since we're not changing the representation (the node graph) based on application code, we're still providing a facility for converting from the node graph to a native data structure that is application specific. Taking this into account, I tend to agree that it makes sense to leave such facility out of the library, making the user responsible for either (1) fix ambiguous representations in the YAML document or (2) implement a `YamlReader` that takes such ambiguities into account.

**Comment by DDuarte** [comment]
Shall I implement a YamlReader for a List[String] because one of the strings might be "true"? Sounds painful :/

**Comment by ruippeixotog** [comment]
A better solution would be to simply write `"true"` instead of `true`. That applies for every ambiguous string.
