### ISSUE TITLE
Support recursive type definition

### ISSUE THREAD

**Issue by zbstof** [jcazevedo/moultingyaml#45]
```
import net.jcazevedo.moultingyaml._

case class Person(name: String, childen: Seq[Person])

object CustomYaml extends DefaultYamlProtocol {
  implicit val format = yamlFormat2(Person)
}
```
gives error:
`No implicits found for parameters evidence$13 YF[Person]`
Is there a workaround for this?

**Comment by marc0x71** [comment]
Hi
have you found a workaround?

Thanks

**Comment by marc0x71** [comment]
I found a solution: lazyFormat

For your scenario this should works

`implicit val format: YamlFormat[Person] = lazyFormat(yamlFormat2(Person))`

**Comment by zbstof** [comment]
Hey, you are right!
The test even covers this exact case:
https://github.com/jcazevedo/moultingyaml/blob/b60661a6f54afd89e21d6246c80106414dc53071/src/test/scala/net/jcazevedo/moultingyaml/AdditionalFormatsSpec.scala#L79-L106
